// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: store_owner.sql

package db

import (
	"context"
)

const createStoreOwner = `-- name: CreateStoreOwner :one
INSERT INTO store_owners (
  user_id,
  store_id
) VALUES (
  $1, $2
) RETURNING user_id, store_id, added_at
`

type CreateStoreOwnerParams struct {
	UserID  int64 `json:"user_id"`
	StoreID int64 `json:"store_id"`
}

func (q *Queries) CreateStoreOwner(ctx context.Context, arg CreateStoreOwnerParams) (StoreOwner, error) {
	row := q.db.QueryRowContext(ctx, createStoreOwner, arg.UserID, arg.StoreID)
	var i StoreOwner
	err := row.Scan(&i.UserID, &i.StoreID, &i.AddedAt)
	return i, err
}
